import { expect, test } from "@playwright/test";

test("customer enquiry persists through owner approval and outcome", async ({ page, browser }) => {
  await page.goto("/login");
  await page.getByTestId("email").fill("owner@demo-hvac.test");
  await page.getByRole("button", { name: "Sign in", exact: true }).click();
  await page.waitForURL("**/inbox");
  await page.goto("/callbacks");
  const enable = page.getByRole("button", { name: "Enable form", exact: true });
  await expect(page.getByText(/Accepting enquiries|Disabled/, { exact: true })).toBeVisible();
  if (await enable.isVisible()) await enable.click();
  const formLink = page.getByRole("link", { name: "Open customer form" });
  await expect(formLink).toBeVisible();
  const customer = await browser.newContext();
  const form = await customer.newPage();
  const name = `Callback-${Date.now()}`;
  await form.goto(new URL((await formLink.getAttribute("href"))!, page.url()).href);
  await form.getByLabel("Name", { exact: true }).fill(name);
  await form.getByLabel("Callback number").fill("07700 900123");
  await form.getByLabel("Email", { exact: true }).fill("callback@example.test");
  await form.getByLabel("Postcode").fill("N13 4SD");
  await form.getByLabel("Job details").fill("A routine boiler service please.");
  await form.getByLabel("Preferred callback date, time and time zone").fill("20 October 2026, 14:00 UK time");
  await form.getByRole("checkbox").check();
  await form.getByRole("button", { name: "Request callback", exact: true }).click();
  await expect(form.getByRole("heading", { name: "Request received" })).toBeVisible();
  await customer.close();
  const card = page.locator("section", { has: page.getByRole("heading", { name, exact: true }) });
  await expect(card).toBeVisible({ timeout: 15000 });
  await card.getByLabel("Callback window").fill("21 October 2026, 10:00 UK time");
  await card.getByRole("button", { name: "Approve callback" }).click();
  await expect(card.getByText("scheduled", { exact: true })).toBeVisible();
  await page.reload();
  await expect(card.getByText("21 October 2026, 10:00 UK time", { exact: true })).toBeVisible();
  await card.getByRole("button", { name: "Mark completed" }).click();
  await expect(card.getByText("completed", { exact: true })).toBeVisible();
  await page.reload();
  await expect(card.getByText("completed", { exact: true })).toBeVisible();
});
